runtime: nodejs

service: frontend

env: flex

handlers:
  - url: /(.*\..+)$
    static_files: build/\1
    upload: build/(.*\..+)$
    secure: always
  
  - url: /.*
    static_files: build/index.html
    upload: build/index.html
    secure: always

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10