runtime: nodejs18
service: default
handlers:
  - url: /api/.*
    script: auto
  - url: /
    static_files: build/index.html
    upload: build/index.html
  - url: /(.*)
    static_files: build/\1
    upload: build/(.*)